require("after.lazygit")
require("after.leap")
require("after.lsp")
require("after.nvimtree")
require("after.telescope")
require("after.toggleterm")
require("after.treesitter")
require("after.comment")